env:
  browser: true
  commonjs: true
  es6: true
extends: ["airbnb-base", "plugin:react/recommended"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2018
rules: 
  semi: 
    - error
    - always
  quotes:
    - error
    - single
  no-multi-spaces: 0
  one-var: 0
  no-console: 0
  linebreak-style: 0
  no-underscore-dangle: ["error", { "allow": ["_id"] }]
  max-nested-callbacks: ["error", 3]
  max-params: ["error", 8]
  max-depth: ["error", 5]
  max-lines-per-function: ["error", 80]
  complexity: ["error", 8]
  class-methods-use-this: 0
