env:
  browser: true
  commonjs: true
  es6: true
extends: ["airbnb-base", "plugin:react/recommended"]
plugins: ["react-hooks"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2018
rules: 
  semi: 
    - error
    - always
  quotes:
    - error
    - single
  no-multi-spaces: 0
  one-var: 0
  no-console: 0
  linebreak-style: 0
  no-underscore-dangle: ["error", { "allow": ["_id", "_isMounted"] }]
  max-nested-callbacks: ["error", 4]
  max-params: ["error", 8]
  max-depth: ["error", 5]
  complexity: ["error", 16]
  class-methods-use-this: 0
  import/no-unresolved: [2, { "caseSensitive": false }]
  no-param-reassign: ["error", { "props": true, "ignorePropertyModificationsFor": ['draft']}]
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
